### ISSUE TITLE
When will this be implemented?

### ISSUE THREAD

**Issue by xamir82** [sqids/sqids-dotnet#2]
Hi. I want to use this in a .NET project, I'd like to know whether this is being implemented or should I just go back to Hashids.net instead?

**Comment by 4kimov** [comment]
@xamir82 It's in the pipeline to be implemented, but we haven't gotten around to it yet. Hashids is definitely still the way to go, but keep in mind that future Sqids IDs will not be compatible.

@ullmark Are you available to port this one over?

**Comment by vyrotek** [comment]
If someone is interested in kicking off this package, feel free to take this gist as starting point. 

https://gist.github.com/vyrotek/5060f9069b2998850de966a0d57349f5

It's a straight conversion of the TS sqids package. I've only tested it against the basic scenarios on the readme but seems to work.

It should definitely be optimized with more proper C# techniques. 😅

**Comment by 4kimov** [comment]
@vyrotek Thanks for the gist! Straight conversion of the spec file is absolutely fine (optimizing language-specific code can come later). The only things that's missing is converting the few unit test files, and I'm sure modern LLMs can help with that. Would you like to be added as a maintainer so you can turn your gist into an actual library?

**Comment by aradalvand** [comment]
@4kimov I made some basic C#-specific improvements to @vyrotek's implementation: https://gist.github.com/aradalvand/5e1b6f90de4324eaac11e20da29225aa

Including but not limited to:

- Use file-scoped namespaces
- Remove calls to `.ToCharArray()` wherever unnecessary.
- Change the `Sqids` class name to `SqidsGenerator` — it's an official bad practice to have types with the same name as their enclosing namespace, and it doesn't let the user actually reference the type after `using` the namespace
- Use `ArgumentException` instead of the generic `Exception` whenever user input is problematic.
- Use `var` wherever the type was being specified twice (e.g. `List<char> list = new List<char>()`)
- Get rid of the `SqidsHelper` class
- Extract `minAlphabetLength` into a constant.
- Use `params` for `Encode` to make usage more convenient.
- Make private helpers static.
- Use two constructors as opposed to one with an optional parameters since that's more common and generally preferred in .NET (primarily because the default constructor could have its own `<summary>`)
- Use `Array.Empty<int>()` when returning an empty array (which uses a singleton under the hood and therefore avoids creating a new array each time).
- Improve variable names (e.g. use `result` instead of `ret`, in C# names are normally not abbreviated)
- Make `MaxValue` and `MinValue` constants (are they even necessary)
- Remove the `Random` instantiation from `Shuffle` because it wasn't even used.
- Improve exception messages

**Comment by ullmark** [comment]
> @ullmark Are you available to port this one over?

@4kimov  Sorry I’m on vacation so slow answer. 😃 I haven’t really maintained Hashids much in the later years it’s been mainly @manigandham. Maybe he is interested in create the new one? I don’t think I am.

**Comment by aradalvand** [comment]
Update: I went ahead and did some of the perf-based refactorings I mentioned (e.g. using `Span`, among other things), and achieved ~3x-4x improvement in both speed and memory allocation — here's some benchmark results:
```
|                  Method |         Mean |       Error |       StdDev | Allocated |
|------------------------ |-------------:|------------:|-------------:|----------:|
| OldImplementationEncode |   4,061.5 ns |    34.17 ns |     28.53 ns |    3840 B |
| NewImplementationEncode |   1,375.5 ns |    23.68 ns |     29.95 ns |    1152 B |
|        HashidsNetEncode |   1,260.2 ns |     5.84 ns |      4.87 ns |     200 B |
| OldImplementationDecode | 145,161.4 ns | 6,235.09 ns | 16,963.03 ns |    2392 B |
| NewImplementationDecode |     912.3 ns |    18.09 ns |     22.88 ns |     160 B |
|        HashidsNetDecode |   1,460.0 ns |     5.00 ns |      4.18 ns |      56 B |
```

The new gist: https://gist.github.com/aradalvand/e1b8eaca27dd643f78316a5cb87f589e

It can still be optimized further; though I think this would make a pretty decent first version.
@4kimov I'd be willing to be added as a maintainer and take on the project if you want. Let me know.

**Comment by 4kimov** [comment]
@aradalvand Bravo on the improvements! :clap: Added you as a maintainer. Once the lib / package / tests are done, I'll update the site

@ullmark Thanks for the heads up & @manigandham appreciate the Hashids updates!

**Comment by vyrotek** [comment]
Thanks for taking this on @aradalvand! Awesome to see the .NET community jump on this so quickly.

**Comment by aradalvand** [comment]
@vyrotek No problem! Thanks a lot to you for doing the initial implementation! Without it I would've been too lazy to do this! :P

**Comment by aradalvand** [comment]
v1 has been [released](https://github.com/sqids/sqids-dotnet/releases/tag/v1.0.0) — so closing this (@xamir82 feel free to open other issues if there's anything else you want to ask).

@4kimov We have [tests](https://github.com/sqids/sqids-dotnet/tree/main/test/Sqids.Tests) and the [NuGet package](https://nuget.org/packages/Sqids) is also now available, so you might want to update the website and add .NET as an available implementation.

**Comment by 4kimov** [comment]
@aradalvand Good job, but do have a question tho. I can see that the tests are not 1:1 with the spec. For example, minLength tests don't test for the same IDs, and uniques test file is blank. The tests from the spec took some time to assemble because they cover a few good edge cases. Is there a way to get each converted to C# so we can be sure the generated IDs match for all kinds of scenarios (and therefore match with other libraries)?

**Comment by aradalvand** [comment]
@4kimov I didn't actually know 1:1 correspondence with the spec was expected when it comes to the tests.
Okay, I'll try and see if I can replicate them.

As for the uniqueness tests specifically, I was under the impression that those were essentially testing the algorithm, rather than the implementation. Do they make sense for individual implementations as well?

**Comment by 4kimov** [comment]
@aradalvand Cool, yeah the spec tests do cover the tricky parts, so having *at least them* would be a good idea. Feel free to separate `encode` and `decode` and do whatever else is appropriate for C#. The main goal is to generate identical IDs given specified params.

- The uniques test file is there to check that every generated ID really is unique. It usually takes a while to run. It does mainly test the algorithm and not individual langs, so I look at it as a safety mechanism just to be sure the worst doesn't happen.
- The shuffle test file is there just to check how well consistent shuffle function works. The other tests will for sure run the internal shuffle function, so it's not necessary to implement this one. You can skip it.
- The other test files should be pretty straightforward and just test different params.

**Comment by aradalvand** [comment]
@4kimov Got it. I'll do a rewrite of the tests.

**Comment by aradalvand** [comment]
@4kimov The tests are now identical to the ones in the spec (all passing); you can check them out [here](https://github.com/sqids/sqids-dotnet/tree/main/test/Sqids.Tests).

I might refactor them a little bit to .NETify them a bit more, but I'll make sure not to break the consistency with the spec tests and preserve the same exact scenarios and values, I'll keep that in mind.

**Comment by 4kimov** [comment]
Right on. Good job @aradalvand :+1: 

A few follow-up items:
- Do the code examples look correct or would you like me to .NETify anything? https://sqids.org/dotnet
- We should probably also give some simple examples [here](https://github.com/sqids/sqids-dotnet/tree/main#examples). Here's a very basic example for Go: https://github.com/sqids/sqids-go#examples

**Comment by aradalvand** [comment]
@4kimov
> Do the code examples look correct or would you like me to .NETify anything? https://sqids.org/dotnet

They are totally correct. The only thing I would say though is that you don't have to manually `new` up an array when calling encode, you could pass the numbers directly like so:
```csharp
string id = sqids.Encode(1, 2, 3); // "8QRLaD"
```
A bit less verbose.

> We should probably also give some simple examples [here](https://github.com/sqids/sqids-dotnet/tree/main#examples). Here's a very basic example for Go: https://github.com/sqids/sqids-go#examples

Yeah the README is not complete yet, I'll make sure to put some more examples on there.

**Comment by 4kimov** [comment]
@aradalvand Cool, thank you for the heads up. Adjusted.
