### ISSUE TITLE
Do you have example of using this with a custom JSON converter?

### ISSUE THREAD

**Issue by grosch-intl** [sqids/sqids-dotnet#27]
I'm using minimal API with .NET 7 and I wanted to add an attribute to my ID fields so that when the JSON encoding/decoding happens, it automatically runs it through this library.  The issue I'm having is that when I call `builder.Services.ConfigureHttpJsonOptions` there's not an `IServiceProvider` available to pass to the custom converter, meaning it doesn't have access to the injected `SqidsEncoder`.

I'm wanting to do something like this:

```csharp
public sealed class SqidJsonConverter : JsonConverter<int> {
    public override int Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) {
        if (reader.GetString() is not string encoded)
            throw new JsonException();

        return options
            .GetServiceProvider()
            .GetRequiredService<SqidsEncoder<int>>()
            .Decode(encoded)
            .FirstOrDefault();
    }

    public override void Write(Utf8JsonWriter writer, int value, JsonSerializerOptions options) {
        var sqid = options.GetServiceProvider().GetRequiredService<SqidsEncoder<int>>();

        writer.WriteStringValue(sqid.Encode(value));
    }
}
```

**Comment by LeaFrock** [comment]
How about creating a Sington `SqidsEncoder` manually?

```csharp
    var opt = configuration.GetSection("Sqid").Get<SqidOption>();
    var encoder = new SqidsEncoder<int>(new SqidsOptions() { MinLength = opt.MinLength, Alphabet = opt.Alphabet });
    services.AddSingleton(encoder);
    builder.Services.ConfigureHttpJsonOptions(opt =>
    {
        opt.SerializerOptions.Converters.Add(new SqidJsonConverter(encoder));
    });

public sealed class SqidJsonConverter(SqidsEncoder<int> encoder) : JsonConverter<int>
{
    public override int Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.GetString() is not string encoded)
            throw new JsonException();

        return encoder.Decode(encoded).FirstOrDefault();
    }

    public override void Write(Utf8JsonWriter writer, int value, JsonSerializerOptions options)
    {
        writer.WriteStringValue(encoder.Encode(value));
    }
}
```

**Comment by grosch** [comment]
@LeaFrock Sorry I'm still struggling with this. The SqidJsonConverter has to take a parameterless constructor in order to be able to put it on a property.  If I do this in my DTO:

```cs
    [JsonConverter(typeof(SqidJsonConverter))]
    public int Id { get; init; }
```

Then the DI fails with this message:
> InvalidOperationException: The converter specified on 'DTS.Server.Orders.DTO.CreateOrderDTO.StationId' does not derive from JsonConverter or have a public parameterless constructor.

Also, would you add an interface for this?  I'd like to be able to inject an `ISqidsEncoder<int>` into my stuff instead of the actual class to help with testing and other stuff.  Thanks.

**Comment by grosch** [comment]
OK, I ended up solving it by making the encoder a static property of the converter, which essentially makes it a singleton.

```cs

public sealed class SqidJsonConverter : JsonConverter<int> {
    private static readonly SqidsEncoder<int> _encoder = new(new() {
        Alphabet = "igOELz2JKI86N3b90Zvq7jypPlAhTrMdVFktuRsQUDCxwceBf5Y4Hm1WXoaGSn"
    });

    public override int Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) {
        if (reader.GetString() is not string encoded)
            throw new JsonException();

        ...
    }

    public override void Write(Utf8JsonWriter writer, int value, JsonSerializerOptions options) => writer.WriteStringValue(_encoder.Encode(value));
}
```

**Comment by LeaFrock** [comment]
@grosch Well, this issue is nothing with this library in fact. It's about how to use STJ in ASP.NET Core.

You'd better use `JsonConverterFactory` here which avoids the hard codes of encoder. The following is a demo for your reference.

```c#
    public sealed class SqidJsonConverter(SqidsEncoder<int> encoder) : JsonConverter<int>
    {
        internal static SqidJsonConverter Instance { get; set; } = default!;

        public override int Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            if (reader.GetString() is not string encoded)
                throw new JsonException();

            return encoder.Decode(encoded).FirstOrDefault();
        }

        public override void Write(Utf8JsonWriter writer, int value, JsonSerializerOptions options)
        {
            writer.WriteStringValue(encoder.Encode(value));
        }
    }


    public sealed class SqidJsonConverterFactory : JsonConverterFactory
    {
        public override bool CanConvert(Type typeToConvert)
            => typeToConvert == typeof(int);

        public override JsonConverter? CreateConverter(Type typeToConvert, JsonSerializerOptions options)
            => SqidJsonConverter.Instance;
    }
```

Then initialize the instance of `SqidJsonConverter` in `Program.cs`,

```c#
var encoder = new SqidsEncoder<int>(new SqidsOptions() { MinLength = 4, Alphabet = "igOELz2JKI86N3b90Zvq7jypPlAhTrMdVFktuRsQUDCxwceBf5Y4Hm1WXoaGSn" });
builder.Services.AddSingleton(encoder);
SqidJsonConverter.Instance = new(encoder);
```

Let's take the official template `WeatherForecast` for example,

```c#
public sealed class WeatherForecast
{
    [JsonConverter(typeof(SqidJsonConverterFactory))]
    public int TemperatureC { get; set; }

    public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);
}
```

You'll see the json like below,

```json
{
    "temperatureC": "8hR2",
    "temperatureF": 82
}
```

If you want all `int`s convert to sqids, you don't even need to claim the attribute. When you're using `Controller`,

```c#
builder.Services.AddControllers()
    .AddJsonOptions(opt =>
    {
        opt.JsonSerializerOptions.Converters.Add(new SqidJsonConverterFactory());
    });
```  

And when using mini api,

```c#
builder.Services.ConfigureHttpJsonOptions(opt =>
{
    opt.SerializerOptions.Converters.Add(new SqidJsonConverterFactory());
});
```

Remove the `JsonConverterAttribute` and you can still see the sqids,

```json
{
    "temperatureC": "c5d9",
    "temperatureF": "IX9z"
}
```

**Comment by aradalvand** [comment]
@grosch-intl Does @LeaFrock's solve your issue? Can we close this?

**Comment by LeaFrock** [comment]
>  would you add an interface for this? I'd like to be able to inject an ISqidsEncoder into my stuff instead of the actual class to help with testing and other stuff.

IMO, this library is small and solid so that the abstraction is not necessary enough. The abstraction should be made by the upper developers. For example, write a class and interface which encapsulates `SqidsEncoder`(taking it as a internal field or property).

It's more meaningful since you may replace `Sqids` one day but you don't need to change your own interface. And it does help with testing and other stuff, too.

**Comment by grosch** [comment]
> @grosch-intl Does @LeaFrock's solution solve your problem? Can we close this issue?

Yes, thanks.
